### ISSUE TITLE
tsc compile fails with "Unreachable code detected" error

### ISSUE THREAD

**Issue by onurturgay** [darkf/darkfo#98]
`..:darkfo postexitus$ tsc
src/scripting.ts(198,5): error TS7027: Unreachable code detected.
src/scripting.ts(202,6): error TS7027: Unreachable code detected.
src/scripting.ts(208,6): error TS7027: Unreachable code detected.
src/scripting.ts(219,5): error TS7027: Unreachable code detected.
src/scripting.ts(225,5): error TS7027: Unreachable code detected.

..:darkfo postexitus$ tsc --version
Version 2.2.1`

**Comment by onurturgay** [comment]
It actually still compiles; just warns. Nothing to see here.

**Comment by darkf** [comment]
Yeah, the only reason I keep it there is because it marks some unimplemented code. I should probably just comment it out or something, really.
